### ISSUE TITLE
[Feature] 建议可以用 `--port` (`-p`) 参数 指定服务器监听的端口

### ISSUE THREAD

**Issue by lgc2333** [TeamFlos/phira-mp#2]
RT

**Comment by chuzouX** [comment]
在phira-mp-server/src/main.rs中可以修改port好像

**Comment by lgc2333** [comment]
> 在phira-mp-server/src/main.rs中可以修改port好像

我知道可以直接改源码，但那样不方便，还需要重新编译一次

**Comment by okatu-loli** [comment]
> > 在phira-mp-server/src/main.rs中可以修改port好像
> 
> 我知道可以直接改源码，但那样不方便，还需要重新编译一次

之前我提交了一个pr，支援了参数指定服务端监听端口，你可以拉下来试试 #9
